window.noname_package={
	character:{
	    diy:'角完杀',
	    standard:'标准',
		refresh:'界限突破',
		shenhua:'神话再临',
		xinghuoliaoyuan:'星火燎原',
		yijiang:'一将成名',
		sp:'璀璨星河',
		yingbian:'文德武备',
		clan:'门阀士族',
		huicui:'群英荟萃',
		xianding:'限定专属',
		sp2:'系列专属',
		extra:'神将',		
		mobile:'移动版',
		shiji:'始计篇',
		sb:'谋攻篇',
		tw:'外服武将',
		collab:'联动卡',
		offline:'线下武将',
		old:'怀旧',
		yxs:'英雄杀',
	},
	card:{
		standard:'标准',
		extra:'军争',
		sp:'忠胆英杰',
		guozhan:'国战',
		zhulu:'逐鹿天下',
		yingbian:'应变篇',
		yongjian:'用间篇',
		zhenfa:'阵法',
		yunchou:'运筹帷幄',
		huanlekapai:'欢乐卡牌',
	},
	play:{
		AIoptimize:'智能AI',
		boss:'诸神降临',
		cardpile:'牌堆补充',
		coin:'富甲天下',
		gujian:'古剑奇谭',
		xianjian:'仙剑奇侠传',
		xuanyuanjian:'轩辕剑',
	},
	mode:{
		identity:'身份',
		guozhan:'国战',
		versus:'对决',
		connect:'联机',
		boss:'挑战',
		doudizhu:'斗地主',
		single:'单挑',
		chess:'战棋',
		brawl:'乱斗',
	},
	submode:{
		identity:{
			normal:'身份模式',
			zhong:'忠胆英杰',
			purple:'3v3v2',
		},
		guozhan:{
			normal:'国战模式',
			mingjiang:'明将国战'
		},
		versus:{
			four:'四人对抗',
			three:'统率三军',
			two:'欢乐成双',
			jiange:'守卫剑阁',
			siguo:'四国争霸',
			standard:'自由对决'
		},
		chess:{
			combat:'战棋模式',
			three:'战棋统率',
			leader:'战棋君主'
		},
		single:{
			normal:'新1v1',
		},
	},
	background:{
		ol_bg:'龙纹',
		xinsha_bg:'古风',
	},
	music:{
		music_phliosophy:'三国杀',
		music_diaochan:'定风波',
		music_shezhan:'今夕何夕',
		music_danji:'峨眉金顶',
		music_jifeng:'玉满堂',
		music_jilve:'极略',
	},
	font:{
		xiaozhuan:'小篆',
		xinwei:'新魏',
		huangcao:'黄草',
		yuanli:'楷体',
		xingkai:'行楷',
		shousha:'手杀',
	},
	theme:{
		woodden:'木纹',
		music:'音乐',
		simple:'简约'
	}
};
